[application]
name = "fwm-web"
default_platform = "web"

out_dir = "dist"
asset_dir = "public"

[web.app]
title = "ğŸ¢ FWM Playground"

[web.watcher]
index_on_404 = true
watch_path = ["src"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[application.plugins]
available = true
required = []
